version: '2'

services:
  gitblit:
    image: 'gitblit/gitblit:1.9.1'
    container_name: gitblit
    restart: always
    ports:
      - '8282:8080'
      - '8443:8443'
      - '9418:9418'
      - '29418:29418'
      - '2222:22'
    volumes:
      - './RedmineData/redmine/files/gitblit_data:/var/opt/gitblit'
